version: "2.1"
services:
  web:
    image: alerta/alerta-web:7.4.6
    ports:
      - "127.0.0.1:9084:8080"
    depends_on:
      - db
    volumes:
      - /var/local/docdoc/docker/alerta/telegram.j2:/app/telegram.j2
      - /var/local/docdoc/docker/alerta/inhibit.yaml:/app/inhibit.yaml
      - /var/local/docdoc/docker/alerta/alertad.conf:/app/alertad.conf
      - /var/local/docdoc/docker/alerta/alerta_enhance.py:/venv/lib/python3.7/site-packages/alerta_enhance.py
      - /var/local/docdoc/docker/alerta/alerta_telegram.py:/venv/lib/python3.7/site-packages/alerta_telegram.py
      - /var/local/docdoc/docker/alerta/telegram.py:/venv/lib/python3.7/site-packages/alerta/webhooks/telegram.py
    environment:
      #      - DEBUG=True+
      - BASE_URL=/api
      - DASHBOARD_URL=https://alerta.example.com
      - USE_PROXYFIX=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - PLUGINS=reject,blackout,normalise,enhance,telegram
      - COMPOSE_PROJECT_NAME=alerta
      - TELEGRAM_TOKEN=<your options>
      - TELEGRAM_CHAT_ID=<your options>
      - TELEGRAM_TEMPLATE=/app/telegram.j2
      - TELEGRAM_SOUND_NOTIFICATION_SEVERITY=security,critical,major
      - TELEGRAM_WEBHOOK_URL=https://alerta.example.com/api/webhooks/telegram?api-key=<your options>
      - BLACKOUT_DURATION=86400
      - AUTH_PROVIDER=google
      - OAUTH2_CLIENT_ID=<your options>
      - OAUTH2_CLIENT_SECRET=<your options>
    restart: always
  db:
    image: postgres
    volumes:
      - /opt/prometheus/alerta/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
